module.exports = (api, options) => {
  api.extendPackage({
    scripts: {
      serve: 'TAILWIND_MODE=watch vue-cli-service serve',
      build: 'vue-cli-service build',
      'test:unit': 'vue-cli-service test:unit',
      lint: 'vue-cli-service lint',
    },
    dependencies: {
      axios: '^0.21.1',
      'core-js': '^3.6.5',
      'date-fns': '^2.20.0',
      vue: '^3.0.0',
      'vue-i18n': '^9.0.0',
      'vue-router': '^4.0.0-0',
      vuex: '^4.0.0-0',
    },
    devDependencies: {
      '@vue/cli-plugin-babel': '~5.0.0',
      '@vue/cli-plugin-eslint': '~5.0.0',
      '@vue/cli-plugin-router': '~5.0.0',
      '@vue/cli-plugin-unit-jest': '~5.0.0',
      '@vue/cli-plugin-vuex': '~5.0.0',
      '@vue/cli-service': '~5.0.0',
      '@vue/compiler-sfc': '^3.0.0',
      '@vue/eslint-config-standard': '^5.1.2',
      '@vue/test-utils': '^2.0.0-0',
      autoprefixer: '^10.4.7',
      'babel-eslint': '^10.1.0',
      eslint: '^7.32.0',
      'eslint-plugin-import': '^2.20.2',
      'eslint-plugin-node': '^11.1.0',
      'eslint-plugin-promise': '^4.2.1',
      'eslint-plugin-standard': '^4.0.0',
      'eslint-plugin-vue': '^7.0.0',
      'lint-staged': '^11.1.2',
      mockjs: '^1.1.0',
      'node-sass': '^4.12.0',
      postcss: '^8.4.14',
      'postcss-import': '^12.0.1',
      'sass-loader': '^8.0.2',
      stylelint: '^13.12.0',
      'stylelint-config-prettier': '^8.0.2',
      'stylelint-config-sass-guidelines': '^8.0.0',
      'stylelint-config-standard': '^21.0.0',
      "tailwindcss": "^3.1.4",
      typescript: '~3.9.3',
      'vue-jest': '^5.0.0-0',
    },
    gitHooks: {
      'pre-commit': 'lint-staged',
    },
    'lint-staged': {
      '*.{js, vue}': ['vue-cli-service lint'],
      '*.{vue, scss, css}': ["stylelint '**/*.{vue, scss, css}'"],
    },
    browserslist: ['> 1%', 'last 2 versions', 'not dead'],
  })
  api.render('./template')
}
